/* Replace with your SQL commands */
DROP TYPE IF EXISTS user_type CASCADE;
DROP TYPE IF EXISTS status CASCADE;
DROP TABLE IF EXISTS user_info CASCADE;
DROP TABLE IF EXISTS company CASCADE;
DROP TABLE IF EXISTS job_opening CASCADE;
DROP TABLE IF EXISTS application CASCADE;